// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-NNNv3t72fEin-_qfeZD8IU8k0oC5Ds',
    appId: '1:1018536310633:web:734a410ed6523bae622ff8',
    messagingSenderId: '1018536310633',
    projectId: 'weathertennis-87368',
    authDomain: 'weathertennis-87368.firebaseapp.com',
    storageBucket: 'weathertennis-87368.appspot.com',
    measurementId: 'G-T29BJTXQHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNActXVzSS_GsS-ZwlOwn600mLgXDVlQ0',
    appId: '1:1018536310633:android:3d45db86c1c09abc622ff8',
    messagingSenderId: '1018536310633',
    projectId: 'weathertennis-87368',
    storageBucket: 'weathertennis-87368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CYi0XTbcUWcMfp5Zkpr_LtjzjjMtERM',
    appId: '1:1018536310633:ios:7c12b494c8e8b8bc622ff8',
    messagingSenderId: '1018536310633',
    projectId: 'weathertennis-87368',
    storageBucket: 'weathertennis-87368.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CYi0XTbcUWcMfp5Zkpr_LtjzjjMtERM',
    appId: '1:1018536310633:ios:7c12b494c8e8b8bc622ff8',
    messagingSenderId: '1018536310633',
    projectId: 'weathertennis-87368',
    storageBucket: 'weathertennis-87368.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-NNNv3t72fEin-_qfeZD8IU8k0oC5Ds',
    appId: '1:1018536310633:web:1186158fed163217622ff8',
    messagingSenderId: '1018536310633',
    projectId: 'weathertennis-87368',
    authDomain: 'weathertennis-87368.firebaseapp.com',
    storageBucket: 'weathertennis-87368.appspot.com',
    measurementId: 'G-L7DHTD1W1H',
  );
}
